const baseUrl = "https://dev-api.sharparchive.com/api/";
export default baseUrl;

export const USER_PROFILE = "/server/user/profile/";
export const forgotPassword = "/server/user/forgot/";
export const passwordReset = "/server/user/reset/";
export const INTRO = "/server/get/intro/";
export const INDUSTRIES = "/server/get/industries";
export const ABOUT = "/server/get/about/";
export const GUEST_FAQ = "/server/get/guest-faq/";
export const SEARCH = "/server/search/";
export const CARDINFO = "/server/card/";
export const PAYMENT_METHOD = "/server/payment/method/";
export const PAYPAL_PAYMENT = "/server/paypal/";
export const PURCHASE_ORDER = "/server/order/";
export const REGISTER = "/server/user/create-new-user/";
export const FEED_COSTS = "/server/get/cost/";
export const EMAIL_VERIFY = "/server/user/verify-email/";
export const RESEND_EMAIL = "/server/user/resend-email-code/";
export const USER_LOGIN = "/server/security/login/";
export const USER_LOGOUT = "/server/security/logout/";
export const SECURITY_OTP = "/server/security/otp/";
export const SAVE_PHONE_NUMBER = "/server/user/save-phone-number/";
export const RESEND_PHONE = "/server/user/resend-phone-code/";
export const PHONE_VERIFY = "/server/user/verify-phone/";
export const STORAGE_RATE = "/server/get/storage-rate/";
export const GET_ESTIMATED_COST = "/server/get/estimated-cost/";
export const ADD_FEED_EXPLANATION = "/server/get/feed-explanation/";
export const REVIEWS = "/server/get/reviews/";
export const FAQ = "/server/get/faq/";
export const LANDING_CONTENTS = "/server/get/features/";
export const FEEDS = "/server/social/provider/";
export const PAST_MONTH = "/server/past-month/";
export const SAVE_USER_SEARCH = "/server/user/search/save/";
export const SAVED_SEARCH = "/server/user/search/";
export const SEND_ACCESS_REQUEST = "/server/guest/send-request/";
export const CHECK_GUEST_REQUEST = "/server/guest/check-request/    ";
export const KEY_FEATURES = "/server/get/key-features/";
export const USER_STORAGE = "/server/user/setting/storage/";
export const AVAILABLE_FEEDS = "/server/social/groupable-feeds/";
export const GROUPS = "/server/social/group/";
export const NAMES = "/server/social/feed/";
export const SOCIAL_FEEDS = "/server/social/feed/";
export const SOCIAL_EARLIEST_DATE = "/server/social/earliest-date/";
export const TIME_ZONES = "/server/get/time-zone/";
export const TIME = "/server/user/setting/time/";
export const TIME_ZONE_WISH_DATE_FORMAT = "/server/get/date-format/";
export const ACTIVITY_LOGS = "/server/user/notification/";
export const SOCIAL_ARTICLE = "/server/social/article/";
export const SOCIAL_ARTICLE_LOAD_MORE = "/server/social/article-more/";
export const NEW_USER = "/server/user/friend/";
export const SOCIAL_AUTH = "/server/social/";
export const INVOICE = "/server/invoice/";
export const LATEST_ARCHIVE = "/server/social/latest/";
export const QUESTION = "/server/user/question/";
export const REQUEST_PARTNER = "/server/partner/request/";
export const VERIFY_PARTNER_EMAIL = "/server/partner/verify-email/";
export const CHECK_EMAIL = "/server/user/check-email/";
export const USER_PERMISSIONS = "/server/get/user-permissions/";
export const ALERT_PERMISSIONS = "/server/get/alert-permissions/";
export const CHECK_ONETIME_TOKEN = "/server/user/check-password-token/";
export const SET_NEW_PASSWORD = "/server/user/set-new-password/";
export const FEED_COMMENTS = "/server/social/comment/";
export const ALL_MESSAGE_PERSONS = "/server/social/chat/";
export const SINGLE_CONVERTIONS = "/server/social/message/";
export const GET_MORE_MESSAGES = "/server/social/message-more/";
export const YOUTUBE_TRANSCRIPT = "/server/social/transcript/";
export const YOUTUBE_PLAYLIST = "/server/social/playlist/";
export const YOUTUBE_PLAYLIST_ITEM = "/server/social/playlist-item/";
export const YOUTUBE_PLAYLIST_ITEM_MORE = "/server/social/playlist-item-more/";
export const SECURITY_DEVICE = "/server/security/device/";
export const WEBSITE_ARCHIVE = "/server/social/web/";
export const WEBSITE_HTML = "/server/web/";
export const WEB_SEARCH = "/server/social/web/search/";
export const PARTNER_INFO = "/server/partner/info/";
export const PARTNER_PAYOUT = "/server/partner/payout/";
export const PARTNER_USERS = "/server/partner/users/";

// export const NEW_USER = 'api-fake/add-new-user/'
export const UPDATE_NEW_USER = "api-fake/update-new-user/";
export const GET_ALL_USERS = "api-fake/get-all-users/";

// export const KEY_FEATURES = 'api-fake/get/key-features/'
// export const INTRO = 'api-fake/intro/'
// export const INDUSTRIES = '/api-fake/industries'
// export const LANDING_CONTENTS = 'api-fake/get/features/'
// export const FAQ = 'api-fake/get/faq/'

export const CHECK_ARCHIVE_FEEDS = "api-fake/user/check-archive-feeds/";
export const SOCIALS = "/server/social/archive/";
export const ARCHIVE_DOWNLOAD = "/server/archive/download/";
export const WEBSITES = "api-fake/websites/";
export const SYSTEM_LIBRARY = "api-fake/new-system-alert-libraries";
// export const FEEDS = 'api-fake/feeds'
// export const GROUPS = 'api-fake/groups'
// export const NAMES = 'api-fake/names'
export const NEW_ALERT_EVENTS = "api-fake/new-alert-events";
export const NOTIFICATION_METHODS = "api-fake/notification-methods";
export const NEW_SYSTEM_ALERTS_STORE = "api-fake/new-system-alerts/store";
export const NEW_SYSTEM_ALERT = "api-fake/new-system-alerts/";
export const NEW_SYSTEM_ALERT_DELETE = "api-fake/new-system-alerts/delete/";
export const CLOSE_ACCOUNT_INFO = "api-fake/close-account-info/";
export const ACCOUNT_USER = "api-fake/account/users";
// export const INVOICE_INFO = 'api-fake/invoice-info'
// export const INVOICE_DOWNLOAD = 'api-fake/invoice-download'
// export const AVAILABLE_FEEDS = 'api-fake/available-feeds'
// export const CREATE_NEW_GROUP = 'api-fake/create-new-group'
// export const GET_SINGLE_GROUP = 'api-fake/get-single-group/'
// export const UPDATE_GROUP = 'api-fake/update-group/'
// export const DELETE_GROUP = 'api-fake/delete-group/'
// export const GET_CREATED_GROUP = 'api-fake/get-created-group'
export const SHOW_EDIT_FEED = "api-fake/show-edit-feed/";
export const SOURCE_FEEDS = "api-fake/source-feeds";
export const CHECK_FEED_PASSWORD = "api-fake/check-feed-password";
export const UPDATE_EXISTING_FEED = "api-fake/update-existing-feed/";
// export const SEND_ACCESS_REQUEST = 'api-fake/send/access-request'
export const SAVE_ARCHIVE_FEEDS = "api-fake/save-archive-feeds";
export const SOCIAL_STATUS_CHANGE = "api-fake/socials-status-change";
export const WEBSITE_STATUS_CHANGE = "api-fake/websites-status-change";
// export const TIME_ZONES = 'api-fake/time-zones'
// export const TIME_ZONE_WISH_DATE_FORMAT = 'api-fake/time-zone-wish-date-format/'
export const ACTIVITY_LOGS_PDF_LINKS = "api-fake/activity-logs-pdf-links";
export const SET_DATE_TIME = "api-fake/set-date-time";
export const NEW_SYSTEM_ALERT_STATUS =
  "api-fake/new-system-alerts/status-change";
export const ALERT_BULK_DOWNLOAD = "api-fake/alert-bulk-download";
export const ARCHIVE_BULK_DOWNLOAD = "api-fake/archive-bulk-download";
export const BULK_SOCIALS = "api-fake/bulk-socials";
export const BULK_WEBSITES = "api-fake/bulk-websites";
export const SAVE_ALERT_SEARCH = "api-fake/save-alert-search/";
export const SAVE_PHONE = "api-fake/user/save-phone";
// export const SAVE_USER_SEARCH = 'api-fake/save-user-search/'
export const SAVE_ALERT_STATUS = "api-fake/save-alert-search-status/";
// export const PAST_MONTH = 'api-fake/past-months'
export const USER_SAVE_SEARCH_CONTEXT =
  "api-fake/user-save-search-wise-context/";
export const ALERT_LIBRARY = "api-fake/alertlibrary";
// export const USER_STORAGE = 'api-fake/user/storage'
export const USER_ARCHIVE_FEEDS = "api-fake/user/archive-feeds";
export const USER_STORAGE_COSTS = "api-fake/user/storage-costs";
export const REVIEWED_HITS = "api-fake/reviewed-hits/";
export const REVIEWED_HITS_MAKE_AS_REVIEWED =
  "api-fake/reviewed-hits-make-as-reviewed/";
export const REVIEWED_HITS_ALERT_DELETE =
  "api-fake/reviewed-hits-delete-alert/";

export const HELP_ABOUT = "/server/get/help-about/";
export const HELP_FAQ = "/server/get/help-faq/";
// export const HELP_QUESTION = 'api-fake/help-question/'
export const HELP_PROBLEM = "api-fake/help-problem/";
export const HELP_TROUBLESHOOT = "/server/get/help-troubleshoot/";
export const HELP_CONTACT = "/server/get/help-contact/";

export const SOCIALS_MEDIA_CONTEXT = "api-fake/socials-media-context/";
// export const REVIEWS = 'api-fake/reviews/'
// export const forgotPassword = 'api-fake/forgot-password/'
// export const verifyForgotPasswordOtp = 'api-fake/verify-forgot-password-otp/'
// export const passwordReset = 'api-fake/password-reset/'

export const CHECK_VALID_PASSWORD = "/server/user/check-password/";
